# Generated by Django 4.1.5 on 2023-01-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_slug'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='shop_custom_last_na_5b83ef_idx',
            old_name='store_custo_last_na_e6a359_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='shop_customers',
        ),
    ]
